# PETI8123 Lab 1: Python Basic Operations

<!--

Ex 1.
for row in table_rows:
    if row["humidity"] > 60:
        print(row)

Ex 2.
l = [0, 1]
for i in range(len(l), 10):
    l.append(l[-1] + l[-2])
print(l)

-->

## 1. Working with Numbers

There are two different types of ways that Python uses numeric data:

* whole number integers (int).
* floats (floating point numbers, or decimals).

You can do almost the same things with floats as you can with integers, except the results you get will have a greater precision and decimal points.

Using numeric data types, you can do all kinds of simple arithmetic. Try to run the below cells and understand what is going on.

In [1]:
# You can add and subtract numbers:
5 - 3

2

In [2]:
# Work with negative numbers:
-5 + 2

-3

In [3]:
# As well as multiply and divide:
5 * 2 / 5

2.0

In [4]:
# You can square numbers (to the power of 2) using **:
2**2

4

In [5]:
# Integer division // always returns an integer (floor):
7 // 2

3

In [6]:
# Remainder of division - the number that remains after an integer division:
6 % 3

0

Notice the green lines in the above cells starting with #. These are comments, which are explanatory text that is not executed. You can use comments to briefly illustrate what you are trying to do with the code.

Python uses the general rules of Algebraic Order of Operations, similar to Excel. Arithmetic operations which you wish to run first should be enclosed in brackets.

In [7]:
(5 + 4) / (2 * 5)

0.9

## 2. Working with Strings

The next essential data type to know about is string. String is essentially just text. You can tell Python that something is a string by wrapping it in "quotation marks".

In [8]:
"This is string"

'This is string'

In [9]:
# You can use two types of quotes: either the double ", or the single '
'"Single quotes work too!'

'"Single quotes work too!'

In [10]:
# Just remember to be consistent!
'This "quote" thing is pretty handy"'

'This "quote" thing is pretty handy"'

In [11]:
# What happens if we add numbers as strings?
"15" + "20"

'1520'

In [12]:
# Try it yourself! What do you notice when you add two strings?
"My" + " name"

'My name'

In [13]:
# We can add many strings actually:
"My" + " " + "name"

'My name'

In [14]:
# Try to find out how long a string is:
len("Give me a string")

16

## 3. Functions and Data Type Casting

In the last cell which calculates how long a string is, you are already using a function!

In Python, a function has a form like this: ``function_name(argument1, argument2, ...)`` where the number of arguments can be from zero (no arguments) to many.

In the last example, we used the ``len`` function (which is an abbreviation of *length*) to find the length of the argument (which is the string you passed into the function). In this case, this ``len`` function requires one argument.

Now, we try another function ``print``, which is used to display some values in the output:

In [15]:
print("This is a string.")

This is a string.

It is a great way to "look under the hood" when you are coding. It is also useful when you are looking for issues in the code, you can print out your data where you think things are going wrong.

For the ``print`` function, you can supply as many as arguments you like:

In [16]:
print("I am", 10.5, "years old")

I am 10.5 years old

In [18]:
# Try to run this code (you will error):
len("2020") # unable to len() in numbers, so it should be changed to string

4

The above cell gives an error - integer has no ``len``. That's true because ``2020`` is a number and not a string. But how can we change that to a string? Here we come to another use of functions. Some functions can perform data type coercion, which means converting from one data type to another.

In [19]:
# Try:
str(2020)

'2020'

In [20]:
# Then we can put them together without errors:
len(str(2020))

4

Also, we can convert from a string to a number:

In [21]:
int("1999") + 1

2000

... and convert from floats to integers:

In [22]:
int(3.14159265359), int(3.6), round(3.4), round(3.5)

(3, 3, 3, 4)

### ❓ Question

Which of the following will print 2.0? If they don't, what do they print instead?
1. ``1.0 + float("1")``
1. ``float("1") + float("1.1")``
1. ``1.0 + int("3.1")``
1. ``1.0 + int(float("3.1")) % 2``
1. ``int(1.0) + int(float("1.1"))``

<hr>

Next, we will look at functions of some objects (such as functions of strings). This type of functions is called **methods** of an object. It is denoted by a period "." like this:

In [ ]:
"This is a string".upper()

``upper`` is a method of a string to change its content to uppercase. You can think it as the object (``This is a string``) take the effect of the ``upper`` function.

Similarly, we can convert a string to lowercase and title case:

In [ ]:
print("This is a string".lower())
print("This is a string".title())

## 4. Variables

Think about these cases:
* Do you want to type out the same numbers, and the same string every time you want to use it?
* What about if you wanted to do some math on the number?
* How are you going to save the answer?

Simple! What we can do is to assign these values to a **variable**.

We can do this using the = sign. What this does is to tell the computer to carve out a piece of memory somewhere, give it the name you told it to, and assign it a user-specified value.

In [23]:
# Makes a variable "language" and gives it the value "Python".
language = "Python"

# Tells the computer to find that piece of memory called "language", and then print out its value.
print(language)

Python

In [24]:
# Now variable "language" is still in the memory. We can re-use it if we want:
language.upper()

'PYTHON'

We can also assign the results of an operation into a new variable too:

In [25]:
number = 10
another_number = 3.1
answer = number * another_number

# What do you think will this print out?
print(answer)

31.0

## 5. Conditionals

We can use logical expressions to make our code decides **IF** it should run some code! These decisions are based on a new data type called **Boolean**, which means something is either ``True`` or ``False``.

Let's look at a simple example: If it is summer now, we say it is hot. Then, we can express the same meaning in Python like this:

In [26]:
summer = True  # We simply assign True/False to a variable to indicate it's a Boolean.

if summer:  # If it is summer...
    print("Hot!")

Hot!

What about we want to do something if the condition **is not** satified? We can add a **``else``** statement:

In [27]:
summer = False

if summer:
    print("Hot!")
else:  # Watch here - this is new!
    print("Cold!")

Cold!

We can use comparison as logical expressions too. See below for an example of comparing numbers:

In [28]:
marks = 50

if marks == 50:
    print("Just passed!")

Just passed!

These are the operations that you can use for comparisons:

* ``<``, less than
* ``>``, greater than
* ``<=`` less than or equal to
* ``>=`` greater than or equal to
* ``==``, equals
* ``!=``, does not equal

If you need to have more than one comparison, you need to use ``elif`` (else-if). Try to adjust the ``marks`` below and observe what will happen.

In [29]:
marks = 50

if marks == 50:
    print("Just passed!")
elif marks < 50:
    print("Failed!")
else:
    print("Good!")

Just passed!

## 6. Lists (and the Mighty Brackets [ ])

A list allows you to store many different values, of many different data types, in the same structure.

We can make a list by putting the values into square brackets, \[ \]

In [30]:
# We can make a new (empty) list using the brackets, or the list function:
[]
list()

[]

In [31]:
# To save a list, we need to assign it to a variable:
temp_list = [1, 2.5, 3, "This", []]
print(temp_list)

[1, 2.5, 3, 'This', []]

In [32]:
# Another example - notice the list inside a list:
candy_cupboard = [["doublecoat Tim Tams", "Tim Tams"], "snickers", "mars"]
print(candy_cupboard)

[['doublecoat Tim Tams', 'Tim Tams'], 'snickers', 'mars']

Sometimes we only want to access certain elements, or data, inside a list. We can do by calling the list index, or the position of the data element, from inside the list:

In [33]:
temp_list[1], candy_cupboard[2]

(2.5, 'mars')

Note that Python actually works based on 0-indexing, meaning that it starts counting from 0 instead of 1. This means that if we want to get the first element of our list, we actually have to call ``list[0]``, instead of ``list[1]``.

We can also use negative index numbers to start counting from the end of the list. For example, getting the last element in the list:

In [34]:
candy_cupboard[-1]

'mars'

To add a new data/variable into a list, we can use the .append() method of the list. This adds the newest variable onto the end of the list.

In [35]:
candy_cupboard.append("snickers")
print(candy_cupboard)

[['doublecoat Tim Tams', 'Tim Tams'], 'snickers', 'mars', 'snickers']

If you pass in a variable, the value in the variable will be added to the end of the list:

In [36]:
candy_name = "mars"
candy_cupboard.append(candy_name)
print(candy_cupboard)

[['doublecoat Tim Tams', 'Tim Tams'], 'snickers', 'mars', 'snickers', 'mars']

## 7. For-loops

In Python, for-loops are used to repeat some actions for many times. The typical usages include repeating something with a number of times, and working on something in each element in a list.

Let's look at the first example. The following cell can repeatedly output a string for 5 times:

In [37]:
for i in range(5):  # range(5) means that we count from 0, 1, 2... for 5 times (NOT until 5).
    print(i)

0
1
2
3
4

Similarly, we can inspect elements in a list like list:

In [38]:
for element in candy_cupboard:
    print(element)

['doublecoat Tim Tams', 'Tim Tams']
snickers
mars
snickers
mars

In [39]:
# Great! What do you think about the output of this cell?
for num in [1,4,3,6,5,9,8,2,7,10]:
    print(num)

1
4
3
6
5
9
8
2
7
10

In Python, we can create a list using a for-loop (also known as **list comprehension**). This means that we use the elements produced from a for-loop to form a list. Learn by this example:

In [40]:
[i * 2 for i in range(10)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

Think about why we have the above output.

## 8. Dictionaries

Dictionaries are another kind of data storage structure used by Python. In a list, each item in a list is associated with a numeric index (e.g. 0, 1, 2, 3...); whereas we make our own indices, which are called **keys** in a dictionary.

A dictionary is also known as associative array. Each item in our list is associated with a key.

Fun facts about a dictionary:
* Rather than using an index, like a list, a dictionary uses "keys", typically strings or numbers, that you define.
* Like a list, a dictionary can contain any kind of data type for its values, even other dictionaries or lists!
* Dictionaries consist of key-value pairs, and as they can only be accessed using the "key" names, they are unordered.
* You can make a dictionary by using ``{}`` or the dict function:

In [41]:
# An empty dictionary:
{}
dict()

{}

Put data into a dictionary like this: ``dictionary = {"key1": "value1", "key2": "value2", ...}``

In [42]:
released = {
    "iphone": 2005,
    "iPhone Pod": 2099,
    "iphone3G" : str(2004),
    "iphone3GS": str(2009),
    "iPhone Smart": 2101,
    "iphone4" : 2010,
    "iphone4S": '2011'
}

print(released)

{'iphone': 2005, 'iPhone Pod': 2099, 'iphone3G': '2004', 'iphone3GS': '2009', 'iPhone Smart': 2101, 'iphone4': 2010, 'iphone4S': '2011'}

Getting a value from a dictionary, wrap ``[ ]`` around the key:

In [43]:
released["iphone"]

2005

Adding to your dictionary is simple - you just "call" your dictionary with a new key name, and assign it a value.

In [44]:
released["iphone11"] = 2019
print(released)

{'iphone': 2005, 'iPhone Pod': 2099, 'iphone3G': '2004', 'iphone3GS': '2009', 'iPhone Smart': 2101, 'iphone4': 2010, 'iphone4S': '2011', 'iphone11': 2019}

We can combining lists and dictionaries to represent more complex data. The following image shows a table of data (or tabular data), which is commonly seen in many occasions.

![A table of data](https://ppgweb.s3.amazonaws.com/files/peti8123/python_list_dict.png)

This table visually illustrates the abstraction of the weather forecast for a given city. The weather abstraction has three properties: temperature, humidity and wind. In this case, each row can be represented by a dictionary like this:

In [45]:
{"humidity": 20, "temperature": 78, "wind": 7}

{'humidity': 20, 'temperature': 78, 'wind': 7}

Now we can store a single row of data in a dictionary, but what about the whole table? Because lists can hold a number of elements, we can take advantage of this and put these dictionaries into a list. Notice that adjacent dictionaries are separated by a comma , symbol here:

In [46]:
table_rows = [
    {"humidity": 20, "temperature": 78, "wind": 7},
    {"humidity": 50, "temperature": 61, "wind": 10},
    {"humidity": 100, "temperature": 81, "wind": 5},
    {"humidity": 90, "temperature": 62, "wind": 15},
    {"humidity": 30, "temperature": 84, "wind": 19},
    {"humidity": 0, "temperature": 66, "wind": 28},
    {"humidity": 0, "temperature": 87, "wind": 12},
    {"humidity": 0, "temperature": 68, "wind": 14},
    {"humidity": 0, "temperature": 86, "wind": 4},
    {"humidity": 60, "temperature": 68, "wind": 0}
]

print(table_rows)

[{'humidity': 20, 'temperature': 78, 'wind': 7}, {'humidity': 50, 'temperature': 61, 'wind': 10}, {'humidity': 100, 'temperature': 81, 'wind': 5}, {'humidity': 90, 'temperature': 62, 'wind': 15}, {'humidity': 30, 'temperature': 84, 'wind': 19}, {'humidity': 0, 'temperature': 66, 'wind': 28}, {'humidity': 0, 'temperature': 87, 'wind': 12}, {'humidity': 0, 'temperature': 68, 'wind': 14}, {'humidity': 0, 'temperature': 86, 'wind': 4}, {'humidity': 60, 'temperature': 68, 'wind': 0}]

Now we can try to add one more row to this "table":

In [47]:
table_rows.append({"humidity": 75, "temperature": 60, "wind": 1})
print(table_rows)

[{'humidity': 20, 'temperature': 78, 'wind': 7}, {'humidity': 50, 'temperature': 61, 'wind': 10}, {'humidity': 100, 'temperature': 81, 'wind': 5}, {'humidity': 90, 'temperature': 62, 'wind': 15}, {'humidity': 30, 'temperature': 84, 'wind': 19}, {'humidity': 0, 'temperature': 66, 'wind': 28}, {'humidity': 0, 'temperature': 87, 'wind': 12}, {'humidity': 0, 'temperature': 68, 'wind': 14}, {'humidity': 0, 'temperature': 86, 'wind': 4}, {'humidity': 60, 'temperature': 68, 'wind': 0}, {'humidity': 75, 'temperature': 60, 'wind': 1}]

## ⚠️ Exercises

**1.** Let's continue with the ``table_rows`` variables above. Use a loop to print the rows with humidity **greater than** 60.

In [48]:
table_rows = [
    {"humidity": 20, "temperature": 78, "wind": 7},
    {"humidity": 50, "temperature": 61, "wind": 10},
    {"humidity": 100, "temperature": 81, "wind": 5},
    {"humidity": 90, "temperature": 62, "wind": 15},
    {"humidity": 30, "temperature": 84, "wind": 19},
    {"humidity": 0, "temperature": 66, "wind": 28},
    {"humidity": 0, "temperature": 87, "wind": 12},
    {"humidity": 0, "temperature": 68, "wind": 14},
    {"humidity": 0, "temperature": 86, "wind": 4},
    {"humidity": 60, "temperature": 68, "wind": 0}
]

print(table_rows)

[{'humidity': 20, 'temperature': 78, 'wind': 7}, {'humidity': 50, 'temperature': 61, 'wind': 10}, {'humidity': 100, 'temperature': 81, 'wind': 5}, {'humidity': 90, 'temperature': 62, 'wind': 15}, {'humidity': 30, 'temperature': 84, 'wind': 19}, {'humidity': 0, 'temperature': 66, 'wind': 28}, {'humidity': 0, 'temperature': 87, 'wind': 12}, {'humidity': 0, 'temperature': 68, 'wind': 14}, {'humidity': 0, 'temperature': 86, 'wind': 4}, {'humidity': 60, 'temperature': 68, 'wind': 0}]

In [51]:
# Write your code for Exercise 1 here
for i in table_rows:
  humidity_value = i['humidity']
  if humidity_value > 60:
    print(i)

{'humidity': 100, 'temperature': 81, 'wind': 5}
{'humidity': 90, 'temperature': 62, 'wind': 15}

**2.** Use Python to find the first 10 Fibonacci numbers. To learn more about
Fibonacci numbers, see https://www.cuemath.com/algebra/fibonacci-numbers/.

Hint: How can we get the second last number from a list?

In [57]:
# Write your code for Exercise 2 here
fibonacci_list = []
for i in range(10):
  if i == 0:
    value = 0
  elif i == 1:
    value = 1
  else:
    value = fibonacci_list[-2] + fibonacci_list[-1]
  fibonacci_list.append(value)
print(fibonacci_list)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]